# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61baaa6077dd455cb9577d3bc5da5ed8c2a60a0e720bb42d495203f35ab8125e7623f7235e8884e671c8e20b3a7274aa82abf38be929f4c79acd6c1d4035271b

test:
  secret_key_base: e118c5038777b97b819d222e3d3c7e709abbbb9046be92cb082ee7eb1e8beb2d4cd8622c37604f1aff40b8eb24980dde5eefa44ae2d8c1706d48cd5e170766b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
